title: 'zw1tt3r1on.github.io'
description: "zw1tt3r1on blog site"
baseurl: "/"
url: "https://zw1tt3r1on.github.io"

header_pages:
  - index.md
  - blog.md
  - about.md
  - contact.md

style: dark

footer: '© 2024 <b>zw1tt3r1on</b> Some rights reserved'
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
